name: call-ci
on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  ci:
    uses: projet-ccm2/shared-workflows/.github/workflows/nodejs-ci.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}