name: ci
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    uses: projet-ccm2/shared-workflows/.github/workflows/nodejs-ci.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
